name: SurvivalGamesV3
main: SurvivalGamesV3\SurvivalGamesV3
version: 3.0.3
api: [1.0.0, 2.0.0, 3.0.0]
author: ImagicalGamer
commands:
    bb:
        usage: /bb
        description: A full list of BuildBattle!
