name: BuildBattlePE
main: ImagicalGamer\BuildBattle\Main
version: 0.0.2
api: [1.0.0, 2.0.0, 3.0.0]
author: ImagicalGamer
commands:
    bb:
        usage: /bb
        description: A full list of BuildBattle!
